services:
  bd_postgres:
    image: postgis/postgis
    container_name: city_app_postgres
    environment:
      POSTGRES_USER: amin
      POSTGRES_PASSWORD: my_super_password
      POSTGRES_DB: django_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  gunicorn:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - static:/app/static_backend/
      - media:/app/media/
      - .:/app
    depends_on:
      - bd_postgres
    networks:
      - city_app_backend_network
    command: >
      sh -c "poetry run python manage.py migrate && 
             poetry run gunicorn city_app.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static_backend/
      - media:/media/
    depends_on:
      - gunicorn
    networks:
      - city_app_backend_network

volumes:
  postgres_data:
  static:
  media:

networks:
  city_app_backend_network:
    driver: bridge